# Generated by Django 5.0.3 on 2024-03-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
